### ISSUE TITLE
Add "page selector" to dev preview

### ISSUE THREAD

**Issue by simne7** [identinet/identinet-plugin#22]
We want to be able to test the UI against the different example websites to find out if a new feature is working well for all of them.

Idea:
- add a dropdown/select below the preview 
- dropdown offers no-id, web-id, id-plus, id-did-config, and id-broken options
- once an option is selected the preview reload and displays the selected configuration

**Comment by jceb** [comment]
Support for id-did-config hasn't been implemented, yet. So the option is not listed.
